### ISSUE TITLE
Property 'X' does not exist on type 'IntrinsicAttributes'

### ISSUE THREAD

**Issue by eddie-dunn** [ArnaudBarre/vite-plugin-fast-react-svg#4]
While compiling and running the application works fine in practice, Typescript is having none of it.

I'm getting these kinds of errors:
```
Type '{ fill: string; width: string; height: string; }' is not assignable to type 'IntrinsicAttributes'. Property 'fill' does not exist on type 'IntrinsicAttributes'.
```

This is my tsconfig.json:
```JSON5
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "types": [
      "vitest/globals",
      "vite-plugin-fast-react-svg/types",
      "vite/client",
      "@types/google.maps",
      "@types/dom-serial"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": ".",
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
```

I've no idea why the type overrides aren't picked up properly.

**Comment by ArnaudBarre** [comment]
Hi,

What version of TS are you using?
Does the error still appear without `"@types/dom-serial"` (I don't know what it is but could mess up with the SVG types)

**Comment by eddie-dunn** [comment]
Typescript ^4.9.5.

`dom-serial` just adds types for the [Web Serial](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API) API, and isn't concerned with SVG.

Nevertheless, I tried removing it and, and upgrading Typescript to ^5.0.2 and I still get the same errors.

I have other @types installed via package.json, do you think that might be causing a type collision? I can try removing them.

EDIT:
Apart from causing a bunch of other type errors, removing all foreign types didn't change anything, Typescript still thinks the imported SVG is a string.

**Comment by ArnaudBarre** [comment]
Oh I think this is because you didn't removed the initial `vite-env.d.ts`?

**Comment by eddie-dunn** [comment]
OK, I found a solution.

We have a file `vite-env.d.ts` in the root of the project containing this:
```
/// <reference types="vite/client" />
```

The types in `vite/client` have this declaration:

```
declare module '*.svg' {
  const src: string
  export default src
}
```

This declaration apparently trumped the one in `tsconfig.json`.

The developer who ported our project from CRA to Vite added the declaration file according to this guide: https://vitejs.dev/guide/features.html#client-types

Changing the declaration file to look like this instead solves the problem:

```
/// <reference types="vite-plugin-fast-react-svg/types" />
/// <reference types="vite/client" />
```

Perhaps this is something you should mention in the README?

**Comment by eddie-dunn** [comment]
> Oh I think this is because you didn't removed the initial `vite-env.d.ts`?

That about covers it :)

Isn't that file required? The guide I linked above seems to imply it.

**Comment by ArnaudBarre** [comment]
You can choose to use `/// <reference` or types in tsconfig. I prefer the later, but I should make it clearer in the readme

**Comment by eddie-dunn** [comment]
Right, so both aren't needed? The [Vite docs](https://vitejs.dev/guide/features.html#client-types) seem to imply that with the "Also"
![image](https://user-images.githubusercontent.com/219063/228890453-9e95f6d8-6089-40df-9e07-b7a39f21191d.png)

However that's not a problem with your plugin, but with their documentation, so I'll close this issue now.

Thanks for the help!

**Comment by ArnaudBarre** [comment]
It would be better to clear in both! Thanks for pointing out this ambiguity of the docs

**Comment by eddie-dunn** [comment]
I submitted a PR for you, as well as one for the Vite docs. :)
